### ISSUE TITLE
URLs not being escaped correctly

### ISSUE THREAD

**Issue by theukedge** [hlashbrooke/Seriously-Simple-Podcasting#105]
I haven't dug in to see where this issue is being caused, but if you upload a file with spaces in the file name, the podcast player allows you to download the file, but doesn't allow you to play it, either in the player or in a new window. Instead, because the URL of the audio is stripping the spaces instead of converting them to %20, you get a 404 on the file.

I'm not sure how long this has been going on, but I believe this was working when the podcast episode we noticed this on was published on August 2015 and has since become a problem. I fixed this by manually adding %20 in podcast file URL.

**Comment by hlashbrooke** [comment]
This is actually caused by WordPress core not handling spaces in file names correctly by stripping them out instead of encoding them. I have created [a ticket](https://core.trac.wordpress.org/ticket/36998) to get this fixed, but in the mean time I have manually added the space encoding to this plugin and it is all working now in v1.14.7 that I released yesterday :)
