### ISSUE TITLE
Why have 2 options for downloads: piped via PHP & URL redirect?

### ISSUE THREAD

**Issue by mattiasgeniar** [hlashbrooke/Seriously-Simple-Podcasting#113]
Currently, there are 2 ways a file can be downloaded. All download links point to ```hostname.tld/podcast-download/id/title-name.mp3```, and the path can be one of 2 ways:

1. Either PHP reads the file (```ssp_readfile_chunked```) and sends it to the client
2. Or PHP does a 302 HTTP redirectly to the MP3 file

What's the rationale behind this? Why not redirect the file always and allow the webserver to handle the request, set all relevant headers, perform compression etc.?

The only reason I could think of would be to hide the real location of the MP3 file?

I'm wondering because the last few days I've had a few minor issues with podcast clients that failed to download a file due to custom headers being sent (now resolved via PR's), but I'm not sure if all edge-cases have been handled now.

It might just be easier to skip the ```$referer``` check altogether and always redirect to the real MP3 file?

**Comment by hlashbrooke** [comment]
The reason for this is kind of two-fold:

1. It's partly a legacy thing, where the URL masking was solving an old problem that isn't really a problem anymore.
2. Some podcast players (which seems to occasionally include iTunes, but not all of the time for some reason) don't like the HTTP redirect on the file. They will sometimes refuse to stream a file if it redirects like that.

The second reason is obviously the main one right now, which is why I do the `header` calls and load the file that way. It _does_ mask the raw file URL, which can be considered a security feature in cases where you may want to hide that kind of thing, but the main reason is that it will present the raw data to the podcast player without doing an HTTP redirect.

The other option, of course, is to completely drop the URL rewrites and just serve the raw file URL. This is possible [with a filter](https://www.seriouslysimplepodcasting.com/documentation/podcast-audio-will-not-play-anywhere/#none-of-the-above-options-work), so anyone can do it easily right now and it will work just fine.

However, if you use the raw file like that, then it doesn't trigger the `download_file()` function (as there's no way to pipe the download through PHP), which ultimately bypasses the `ssp_file_download` action hook. The problem with that is that is becomes completely impossible to track the file downloads through WordPress, making [the stats add-on](https://wordpress.org/plugins/seriously-simple-stats/) (and potentially some other future add-ons) unusable. Of course, if you don't care about stats and such then you can go ahead and use the filter.

So that's the background and the reasoning - I'd be happy to look at alternative solutions here if it will help to improve the plugin. Note that one thing I am looking at is replacing the URL rewrites with custom REST API endpoints (#111) as that will improve performance to some degree (WP's URL Rewrite API is notoriously janky) and reduce the amount of code needed to create the custom URLs.

**Comment by mattiasgeniar** [comment]
Thanks for the feedback, that reasoning makes a lot of sense. I'll go ahead and close this.
