### ISSUE TITLE
Set the podcast_episode shortcode to use the current post ID if none is specified

### ISSUE THREAD

**Issue by gingerbeardman** [hlashbrooke/Seriously-Simple-Podcasting#127]
right now I have to specify the post id even if i'm using the shortcode in that very post.

would be simpler if i could ignore posted and it would default to the one in the post.

**Comment by hlashbrooke** [comment]
The `ss_podcast` shortcode is semi-deprecated to be honest as I am working on a way to replace it completely in future versions - it's a clunky shortcode that doesn't really do exactly what you'd expect. It is also, however, designed for showing a list of episodes and not a single episode's content, so I'm not sure it's the best one for what you're wanting to do here.

The shortcode that is designed for showing a single episode's content is `podcast_episode` and currently you _always_ need to specify the episode post ID there in order for it to display anything. I'll update that in the next release so that if no episode ID is specified then it will use the current post's ID.

I'm going to rename this issue to make it more clear what the fix here is going to be.

Thanks for bringing this up!

**Comment by gingerbeardman** [comment]
This is the short code format I was using:

`[podcast_episode episode="123" content="player"]`

i expected to be able to use it like this and have it default to the podcast on the post it's being used on:

`[podcast_episode content="player"]`

**Comment by hlashbrooke** [comment]
Gotcha - yes, I will have this sorted out in the next release :)

**Comment by hlashbrooke** [comment]
FYI - this is now in the `master` branch and will be published when the next release is ready to go :)
