### ISSUE TITLE
Allow to edit the link tag

### ISSUE THREAD

**Issue by pjanaya** [hlashbrooke/Seriously-Simple-Podcasting#43]
I'm currently using your plugin and I think it's great. However I have a problem that I can't solve. I hope you can help me because I don't want to hardcode anything.

I have a webpage for personal stuff: http://www.pabloanaya.com/. I have a podcast with some friends and I'm using my server to store the audios under http://www.pabloanaya.com/fatpixel/. I have created the proper feed using your plugin (http://www.pabloanaya.com/feed/podcast/fatpixel). The problem is that I don't want this in the feed;
    
    <link>http://www.pabloanaya.com</link>

I need this:

    <link>http://www.pabloanaya.com/fatpixel/</link>

In your `feed-template.php` I found this:

    <link><?php esc_url( bloginfo_rss('url') ) ?></link>

I wonder if you can include the link tag as one editable field. Maybe by default should be `bloginfo_rss` but give the opportunity to change it.

What do you think?

Thank you very much and great job!

**Comment by hlashbrooke** [comment]
Thanks for posting this.

I don't think I'll include an editable field for this in the podcast settings - because it will confuse users who don't understand what the `<link>` tag is for. Instead I will add a filter for this to the next release that you can use to modify the contents of the tag dynamically, but the default value will always be `bloginfo_rss('url')`. The filter will be named `ssp_feed_channel_link_tag` and you will be able to use it like this:

```php
add_filter( 'ssp_feed_channel_link_tag', 'modify_podcast_feed_link_tag', 10, 2 );
function modify_podcast_feed_link_tag ( $link, $series ) {
    $link = 'http://www.pabloanaya.com/fatpixel/';
    return $link;
}
```

As you can see you will also be able to use the series slug as the second parameter to make the filter more dynamic.

This will be available in v1.9.8+ :)

**Comment by hlashbrooke** [comment]
Actually - I've worked out a better solution here. I will still add the `ssp_feed_channel_link_tag`, but you probably won't need to use it. Instead of just using the default URL I will always use the URL for the current feed - whether that is the global podcast feed or a feed for a specific series. That way the URL in the `<link>` tag will always be correct and relevant to the content that is currently being viewed.

I will release this in v1.9.8 later this week.

**Comment by pjanaya** [comment]
Man, that sounds great! 

Thanks for your work, you're amazing :D

**Comment by hlashbrooke** [comment]
This is sorted out in v1.9.8 of the plugin that I have just releases. You can see the full release notes here: http://www.seriouslysimplepodcasting.com/documentation/version-1-9-8/

**Comment by pjanaya** [comment]
I'm sorry but I tried the new version and actually this is worse. When iTunes shows the link to the website I don't want the feed link (and I suppose no one wants the feed link). What I'm looking for when I click on the "Website" link is to see the actual website with the episodes. For most people probably `bloginfo_rss('url')` but a custom url like `http://www.pabloanaya.com/fatpixel/` for me.

https://www.dropbox.com/s/5ubkuhg6yb2eaw6/2015-05-05_10-17-05.png?dl=0

**Comment by hlashbrooke** [comment]
Well the filter is still there for you, so you can simply use the snippet I posted above to add a custom URL there. That should work as a solution for you.

**Comment by pjanaya** [comment]
Yes, I will do it that way. I just wanted to tell you because this may affect the previous behavior in other currently deployed podcasts.

**Comment by hlashbrooke** [comment]
I hear you - I'll see what I can do about that in the public release.
