### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by signor-rossi** [hlashbrooke/Seriously-Simple-Podcasting#67]
Hi, I've just translated Seriously Simple Podcasting to german. Where can I upload the po/mo-files?

**Comment by hlashbrooke** [comment]
That's awesome :) You can either upload the files to any file sharing platform and paste the link here, or submit a Pull Request with the files in it. Either way, I will add the translation to the plugin and credit you for it.

Bear in mind that in the latest release (v1.11.2), the text domain was changes to `seriously-simple-podcasting` (in order to match the plugin's slug as is the correct standard). That won't affect your po/mo files at all, other than the file names, but just letting you know :)

**Comment by signor-rossi** [comment]
ok, here you are. 
https://www.dropbox.com/s/u7gd92agn9dlqwb/seriously-simple-podcasting-de_DE.po?dl=0

I avoided totally the use of "you", because in German there is a formal (Du) or informal (Sie) way to use it.

**Comment by hlashbrooke** [comment]
OK great - thanks!

I'll need the `mo` file as well, so please send that too and I'll add this into the next plugin release :)

**Comment by signor-rossi** [comment]
Link to the mo-File:
https://www.dropbox.com/s/7rkula84sb3ly6u/seriously-simple-podcasting-de_DE.mo?dl=0

**Comment by hlashbrooke** [comment]
Thank you! This will be included in the next release (v1.11.3) :)

**Comment by hlashbrooke** [comment]
@signor-rossi: The translation files for this plugin have been moved over to translate.wordpress.org and can now be contributed to from here: https://translate.wordpress.org/projects/wp-plugins/seriously-simple-podcasting/dev.

If you send me your WordPress.org username then I can request to have you added as a translation editor for the German translation. That means that you will be able to approve translation strings submitted by the community :)

**Comment by signor-rossi** [comment]
Hi,
my wordpress-username also is
signor.rossi

Best regards
Felix Sperandio

Am 8. Oktober 2015 12:54:51 MESZ, schrieb Hugh Lashbrooke <notifications@github.com>:

**Comment by hlashbrooke** [comment]
Thanks @signor-rossi - I'll get you added as a translation editor in the next week :)
