### ISSUE TITLE
Feed Customisation

### ISSUE THREAD

**Issue by philo23** [hlashbrooke/Seriously-Simple-Podcasting#91]
I'm looking into adding XML stylesheets into the RSS feed to include a bit more information for anyone clicking through to the podcast feed directly, right now my only option seem to be customising the ``templates/feed-podcast.php`` file directly.

It'd be great if there was some extra hook in place to add some custom XML to that file, or perhaps even include an option to add a stylesheet in the settings.

**Comment by whyisjake** [comment]
There is `do_action( 'rss2_head' );` [here](https://github.com/hlashbrooke/Seriously-Simple-Podcasting/blob/master/templates/feed-podcast.php#L280) in the feed template. You could hook in there.  Based on [this article](http://archive.oreilly.com/pub/a/network/2005/07/01/rss.html) It probably needs to be a little higher up, before the RSS declaration. I can add this in a couple hours, or a PR is welcome!

**Comment by hlashbrooke** [comment]
I've never really thought about this before, but I did some quick research now and I think this could be a really good idea. The stylesheet declaration needs to be right at the top of the feed on the second line (just below the `<?xml` declaration). There is no hook there at the moment, but instead of adding one I think a much better option would be to create a stylesheet that is packaged with the plugin making it much easier to read the podcast RSS feeds.

I will start working on this as soon as I can, but in the mean time if you had a specific idea for how you would format the stylesheet then feel free to submit the PR here :)

**Comment by hlashbrooke** [comment]
I've been kicking around with XSL stylesheets a bit and it seem relatively straight forward. This is what I've put together so far as a stylesheet for the podcast RSS feed:

<img width="1169" alt="screen shot 2016-01-18 at 10 53 30 am" src="https://cloud.githubusercontent.com/assets/1543143/12386960/d5dce5e6-bdd1-11e5-9b59-8509de71c3ef.png">

I'm trying to keep it generic enough, yet still looking good - what do you think @philo23 @whyisjake?

The images are in conditionals, so it will still look just fine if no images exist for the channel or items in the feed.

Due to the nature of XSL, this won't really be editable by site owners unless I can find a way to make it filterable, but I'm not 100% sure that will be possible. Any feedback on what I've put together here would be great as I would like this to go into the next release of the plugin (v1.14) along with some other enhancements I'm working on.

**Comment by philo23** [comment]
That looks really great, I'm glad you're onboard with the idea. Though I'd still personally love to have an option to perhaps set your own XSL stylesheet so there's still an option to customise if you want to, but I agree it's probably best to have a default one anyway.

**Comment by hlashbrooke** [comment]
Great stuff. I'm going to see what I can do with allowing it to be filterable. The easiest way would be to allow you to create a custom `.xsl` file that you can add to your server and then just specify the URL using a filter like `ssp_xml_stylesheet` or something along those lines. That means you could even upload the `.xsl` file to your media library and grab the URL from there - that should make it pretty easy to filter I think.

**Comment by hlashbrooke** [comment]
I've added this to the master branch now. I want to get video podcasting (#84) into v1.14 as well, so will work on that and then release

**Comment by ouija** [comment]
Super late to the party here but figured I'd mention that you can copy the `./templates/feed-podcast.php` and `/templates/feed-stylesheet.xsl`  files from the plugin folder to your template (or child template), then edit this  `./templates/feed-podcast.php` file around line 296 to load the `feed-stylesheet.xsl` file from your template folder:

```
// Get stylehseet URL (filterable to allow disabling or custom RSS stylesheets)
$apply_stylesheet_url = apply_filters( 'ssp_enable_rss_stylesheet', true );
if ( $apply_stylesheet_url ) {
	$stylesheet_url = apply_filters( 'ssp_rss_stylesheet', get_stylesheet_directory_uri() . '/feed-stylesheet.xsl' );
}
```
